# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/prestasafe/erp/models/quote/columns.yaml

# Model Class name
modelClass: Prestasafe\Erp\Models\Quote

# List Title
title: Manage Quotes

# Link URL for each record
recordUrl: prestasafe/erp/quotes/update/:id

# Message to display if the list is empty
noRecordsMessage: backend::lang.list.no_records

# Records to display per page
recordsPerPage: 20

# Display page numbers with pagination, disable to improve performance
showPageNumbers: true

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Default sorting column
# defaultSort:
#     column: created_at
#     direction: desc

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
filter: config_filter.yaml
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt

